### PR TITLE
Add support for floating point seconds as a duration

### LINKED ISSUE #4: Support for float as a duration
Duration should be able to be specified in as `3.5` seconds, especially in the case of a < 1 second countdown is needed.

### PR DESCRIPTION
**Pull request by mduvall**
Fixes https://github.com/gumroad/countdown.js/issues/4.

### CODE REVIEW

**Comment by kn** [comment]
Assuming this is for just accepting floating point seconds as valid duration, I think it's better to just convert float to int at the beginning so that we can keep our code simple.

What do you think?

**Comment by mduvall** [comment]
@kn This commit adds the actual countdown from a float, so doing `new Countdown(2.5...)` will trigger `onComplete` after two full ticks on the interval and sets a timeout for 500ms (the majority of the added code). I thought this abstraction would be useful as a basis to use other units of time that are more granular, ms specifically.

**Comment by kn** [comment]
I see. I think this change makes countdown's behavior harder to understand. e.g. passing 2.5s as a duration makes two ticks and calls `onComplete` after 0.5s from the last tick, where last interval is now 0.5s instead of 1s (which is not usual behavior of counting down.)

Unless there is strong use case for this, I rather keep it simple.

Instead, I think we should force 1s interval by validating/converting duration argument.

Floating point duration makes more sense if we accept variable interval duration I think (not that I think we should do it).

**Comment by mduvall** [comment]
@kn That's fair, it does add a fair amount of complexity for a pretty orthogonal concern. I wanted to use Countdown.js to animate the buttons (similar to a progress bar with the ticker) smoothly and was going to add intervals for ms as an animation hook with the `tickCallback` after this commit. CSS3 transitions could be used as well when I think about it! I'll close for now and we can open this later if somebody else requests it :+1: 

Here's a crappy drawing of what I kind of mean:
transition countdown

**Comment by kn** [comment]
Awesome. Great idea tho! :+1:

**Pull request closed without merging**
